stages:
  - build
  - test
  - deploy
    
build:
  stage: build
  image: node:6.11.1
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
      - package.json
      - server/

test:
  stage: test
  image: node:6.11.1
  services:
    - mongo:3.4
  dependencies:
    - build
  script: 
    - npm run dev

deploy:
  stage: deploy
  variables: 
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    BUILD_TIMESTAMP: date +%s
  image: python:latest
  dependencies:
    - build
  script:
    - apt-get update
    - apt-get install -y zip
    - zip -r teleclaw_backend_api_$BUILD_TIMESTAMP.zip package.json server/ node_modules/
    - pip install awscli
    - aws s3 ls
