stages:
  - build
  - test
  - deploy
    
build:
  stage: build
  image: node:6.11.1
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
      - .

test:
  stage: test
  image: node:6.11.1
  services:
    - mongo:3.4
  dependencies:
    - build
  script: 
    - npm run dev

deploy:
  stage: deploy
  variables: 
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  image: python:latest
  script:
    - apt-get update
    - apt-get install -y zip
    - pip install awscli
    - aws s3 ls
