stages:
  - build
  - test
  - deploy
    
build:
  stage: build
  image: node:6.11.1
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
      - package.json
      - server/

test:
  stage: test
  image: node:6.11.1
  services:
    - mongo:3.4
  dependencies:
    - build
  script: 
    - npm run dev

deploy:
  stage: deploy
  variables: 
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_S3_BUCKET: $AWS_S3_BUCKET
    AWS_DEFAULT_REGION: ap-southeast-1
  image: python:latest
  dependencies:
    - build
  script:
    - apt-get update
    - apt-get install -y zip
    - TIMESTAMP=$(date +%s)
    - ZIP_FILE_NAME="teleclaw_backend_api_$TIMESTAMP.zip"
    - zip -r $ZIP_FILE_NAME package.json server/ node_modules/
    - pip install awscli
    - aws s3 cp $ZIP_FILE_NAME s3://$AWS_S3_BUCKET
    - aws elasticbeanstalk create-application-version --application-name teleclaw_backend_api --version-label test1 --source-bundle S3Bucket=$AWS_S3_BUCKET,S3Key=$ZIP_FILE_NAME
    - aws elasticbeanstalk update-environment --application-name teleclaw_backend_api --environment-name teleclawBackendApi-env --version-label test1
