image: node:6.11.1

services:
  - mongo:3.4

stages:
  - build
  - test
    
start_server:
  stage: build
  script:
    - npm install
    - npm run start

test:
  stage: test
  script: 
    - npm run dev
