image: node:6.11.1

services:
  - mongo:3.4

cache:
  - node_modules/

stages:
  - build
  - test
    
build:
  stage: build
  script:
    - npm install

test:
  stage: test
  script: 
    - npm run dev
