stages:
  - build
  - test
  - deploy
    
build:
  stage: build
  image: node:6.11.1
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  image: node:6.11.1
  services:
    - mongo:3.4
  dependencies:
    - build
  script: 
    - npm run dev

deploy:
  stage: deploy
  image: python:latest
  script:
    - pip install awscli
