runtime: nodejs8
instance_class: F2

automatic_scaling:
  max_instances: 2
  max_idle_instances: 1

env_variables:
  KT_VAR_MONGODB_URL: mongodb://teleClawAdmin:z2CnO9D47RgdrvB@ds163705.mlab.com:63705/teleclaw_production
  FB_APP_SECRET: e1af1950c0642c405a28c1e706059b7c
  FB_CLIENT_ID: 144167082893443
  FB_APP_TOKEN: e4eb506efe7786bf8b772e10c4eaf7e8
  CLOUDINARY_CLOUD_NAME: teleclaw
  CLOUDINARY_API_KEY: 557682748641557
  CLOUDINARY_API_SECRET: OXLI2HwvbmIMvSNTNCSulRgWzjA
  PUSHER_APP_ID: 459456
  PUSHER_KEY: 7fbd034f7c175d877b05
  PUSHER_SECRET: 91f3ce2ba76d0c193da6
  PUSHER_CLUSTER: ap1
  GIZWITS_APPLICATION_ID: 20a365a7564142d3a342916f6d6df937
  GIZWITS_PRODUCT_SECRET: bfe233b5fdcf4d8daaad7c5062399b15
  GIZWITS_PRODUCT_KEY: 0b20eeca92544b888db9ebcc70bee872
  BRAINTREE_MERCHANTID: bw55mtp3fsr6kjc2
  BRAINTREE_PUBLICKEY: bygw36q9vvbg2swn
  BRAINTREE_PRIVATEKEY: 7270339cbee70fb780d5e46bc472e618
  EASYSHIP_TOKEN: prod_Dxo6zX9i0ll5IH+OjoSFBRjy8oOjU7rY6OHWupYr+i4= 
  GMAIL_ADDRESS: teleclaw.live@gmail.com
  GMAIL_PASSWORD: yn;7837U3GDli
  PAPERTRAIL_PORT: 33263
  NODE_ENV: production