version: "3.3"
services:
  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
    volumes:
      - ./test/data/mongo_data:/data/db
  api:
    build: .
    volumes:
      - ./server:/usr/src/app/server
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - NODE_ENV=staging
      - KT_VAR_MONGODB_HOST=${KT_VAR_MONGODB_HOST}
      - KT_VAR_MONGODB_PORT=${KT_VAR_MONGODB_PORT}
      - KT_VAR_MONGODB_USERNAME=${KT_VAR_MONGODB_USERNAME}
      - KT_VAR_MONGODB_PASSWORD=${KT_VAR_MONGODB_PASSWORD}
      - KT_VAR_MONGODB_DATABASE=${KT_VAR_MONGODB_DATABASE}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_SERVICE_KEY_NAME=${FIREBASE_SERVICE_KEY_NAME}
      - FB_APP_SECRET=${FB_APP_SECRET}
      - FB_CLIENT_ID=${FB_CLIENT_ID}
      - FB_APP_TOKEN=${FB_APP_TOKEN}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - PUSHER_APP_ID=${PUSHER_APP_ID}
      - PUSHER_KEY=${PUSHER_KEY}
      - PUSHER_SECRET=${PUSHER_SECRET}
      - PUSHER_CLUSTER=${PUSHER_CLUSTER}
      - GIZWITS_APPLICATION_ID=${GIZWITS_APPLICATION_ID}
      - GIZWITS_PRODUCT_SECRET=${GIZWITS_PRODUCT_SECRET}
      - GIZWITS_PRODUCT_KEY=${GIZWITS_PRODUCT_KEY}