version: "3.3"
services:
  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
    volumes:
      - ./test/data/mongo_data:/data/db
  api:
    build: .
    volumes:
      - ./server:/usr/src/app/server
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - KT_VAR_MONGODB_HOST=mongo
      - KT_VAR_MONGODB_PORT=27017
      - KT_VAR_MONGODB_USERNAME=teleClawAdmin
      - KT_VAR_MONGODB_PASSWORD=123456
      - KT_VAR_MONGODB_DATABASE=teleclaw_dev
